@startuml

Customer --> (Choose events)
Customer --> (Buy ticket)
Customer --> (Cancel ticket)
Customer --> (See ticket history)

newpage

Organizer -->(Create, delete and edit Events<seated and nonseated>)
Organizer -->(Create, delete and edit Location)
Organizer -->(Create, delete and edit Rooms)

@enduml