Sekvensdiagram for registering av ny "Customer" bruker
@startuml

User -> Customer:Register Customer
Customer -> Database:Add customer account
User <-- Database:Return customer account

@enduml