@startuml

Customer --> (Choose events(seated and nonseated)
Customer --> (Buy ticket)
Customer --> (Cancel ticket)
Customer --> (See bought tickets)

newpage

Orginaizer -->(Create, delete and edit Events(Seated and nonseated)
Orginaizer -->(Create, delete and edit redigere Location)
Orginaizer -->(Create, delete and edit redigere rooms)

@enduml