Sekvensdiagram for registering av ny "Customer" bruker
@startuml

TestUserModel -> Customer:Register Customer
Customer -> Database:Add customer account
TestUserModel <-- Database:Return customer account

alt Error
    TestUserModel <-- Customer:Register failed
end
@enduml